clear all
close all
%{
verts = [2 4 3; ...
        2 8 3; ...
        8 4 3; ...
        8 0 3; ...
        0 4 3; ...
        2 6 3; ...
        2 2 3; ...
        4 2 3; ...
        4 0 3; ...
        5 2 3; ...
        5 0 ];
faces = [1  2  3; ...
         1  3  4; ...
         5  6  1; ...
         7  8  9; ...
         11 10 4];
p = patch('Faces',faces,'Vertices',verts,'FaceColor','b');
%}
cam_verts = [0 0 0;...
            1 0.75 0.5;...
            1 0.75 -0.5;...
            1 -0.75 -0.5;...
            1 -0.75 0.5];
faces = [1 2 3 1;...
        2 3 4 5;...
        1 4 5 1;...
        1 4 3 1;...
        1 5 2 1];
figure(1)
clf
p = patch('Faces',faces,'Vertices',cam_verts,'FaceColor',[0.5 0.5 0.5]);
axis equal
grid on
xlim([-2 2])
ylim([-2 2])
zlim([-2 2])


   for i = 1:5
        imageFileName = sprintf('image%d.tif', i);
        imageFileNames{i} = fullfile(matlabroot, 'toolbox', 'vision',...
            'visiondemos', 'calibration', 'webcam', imageFileName);
   end
    
      [imagePoints, boardSize] = detectCheckerboardPoints(imageFileNames);
      
         squareSide = 25;
    worldPoints = generateCheckerboardPoints(boardSize, squareSide);
        cameraParams = estimateCameraParameters(imagePoints, worldPoints)